# This docker-compose file is used to create a development environment for the web application
version: "3.8"

services:
  web:
    image: web
    container_name: WebCont
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres_db
    volumes:
      - .:/app

  # This is a testing instance for development
  postgres_db:
    image: postgres
    container_name: PostgresCont
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=world
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
    driver: local
