# Use the build stage from your original Dockerfile
FROM golang:1.21.4 AS build-stage
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . /app
RUN CGO_ENABLED=0 GOOS=linux go build -o /entrypoint


# Start a new stage for the development environment
FROM build-stage
WORKDIR /app
# Start the application
ENTRYPOINT ["/entrypoint"]
