// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func DynamicIslandTop(text string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style type=\"text/css\">\n\t\t.island {\n\t\t\tbackground-color: whitesmoke;\n\t\t\tposition: absolute;\n\t\t\tleft: 50%;\n\t\t\ttop: 0.4rem;\n\t\t\ttransform: translateX(-50%);\n\t\t\tborder-radius: 20px;\n\t\t\tbox-shadow: 0 1px 2px rgba(0, 0, 0, 0.05);\n\t\t\tmargin-bottom: 3px;\n\t\t\tpadding-left: 0.625rem;\n\t\t\tpadding-right: 0.625rem;\n\t\t\toutline: #52a9ff;\n\t\t}\n\t\t.island-center {\n\t\t\tpadding-left: 0.625rem;\n\t\t\tpadding-right: 0.625rem;\n\t\t\tjustify-content: space-between;\n\t\t\talign-items: center;\n\t\t\tdisplay: flex;\n\t\t\theight: 28px;\n\t\t\tposition: relative;\n\t\t}\n\t\t.popup-title {\n\t\t\tmargin-bottom: 0px;\n\t\t}\n\t\t.popup-title h2 {\n\t\t\tfont-size: 0.8rem;\n\t\t\tfont-weight: 400;\n\t\t\tfont-variant-numeric: slashed-zero;\n\t\t\tfont-variant-ligatures: none;\n\t\t\tmargin: 0;\n\t\t}\n\t\t.popup-close {\n\t\t\ttext-align: right;\n\t\t}\n\t\t.popup-close a {\n\t\t\tcolor: #999;\n\t\t\tfont-size: 20px;\n\t\t\ttext-decoration: none;\n\t\t}\n\t\t.popup-close a:hover {\n\t\t\tcolor: #000;\n\t\t}\n\t</style><div class=\"island\"><div class=\"island-center\"><div class=\"popup-title\"><h2>Link copied!  </h2></div><div class=\"popup-close\"><a href=\"#\" class=\"close-popup\"><i class=\"fa fa-times\"></i></a></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
