// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/zmzlois/LinkGoGo/ent/account"
	"github.com/zmzlois/LinkGoGo/ent/links"
	"github.com/zmzlois/LinkGoGo/ent/schema"
	"github.com/zmzlois/LinkGoGo/ent/session"
	"github.com/zmzlois/LinkGoGo/ent/users"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescFirstName is the schema descriptor for first_name field.
	accountDescFirstName := accountFields[2].Descriptor()
	// account.FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	account.FirstNameValidator = accountDescFirstName.Validators[0].(func(string) error)
	// accountDescLastName is the schema descriptor for last_name field.
	accountDescLastName := accountFields[3].Descriptor()
	// account.LastNameValidator is a validator for the "last_name" field. It is called by the builders before save.
	account.LastNameValidator = accountDescLastName.Validators[0].(func(string) error)
	// accountDescEmail is the schema descriptor for email field.
	accountDescEmail := accountFields[4].Descriptor()
	// account.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	account.EmailValidator = accountDescEmail.Validators[0].(func(string) error)
	// accountDescAvatar is the schema descriptor for avatar field.
	accountDescAvatar := accountFields[5].Descriptor()
	// account.AvatarValidator is a validator for the "avatar" field. It is called by the builders before save.
	account.AvatarValidator = accountDescAvatar.Validators[0].(func(string) error)
	// accountDescDeleted is the schema descriptor for deleted field.
	accountDescDeleted := accountFields[7].Descriptor()
	// account.DefaultDeleted holds the default value on creation for the deleted field.
	account.DefaultDeleted = accountDescDeleted.Default.(bool)
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountFields[8].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() time.Time)
	// accountDescUpdatedAt is the schema descriptor for updated_at field.
	accountDescUpdatedAt := accountFields[9].Descriptor()
	// account.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	account.DefaultUpdatedAt = accountDescUpdatedAt.Default.(func() time.Time)
	// account.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	account.UpdateDefaultUpdatedAt = accountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// accountDescID is the schema descriptor for id field.
	accountDescID := accountFields[6].Descriptor()
	// account.DefaultID holds the default value on creation for the id field.
	account.DefaultID = accountDescID.Default.(func() uuid.UUID)
	linksFields := schema.Links{}.Fields()
	_ = linksFields
	// linksDescURL is the schema descriptor for url field.
	linksDescURL := linksFields[1].Descriptor()
	// links.URLValidator is a validator for the "url" field. It is called by the builders before save.
	links.URLValidator = linksDescURL.Validators[0].(func(string) error)
	// linksDescTitle is the schema descriptor for title field.
	linksDescTitle := linksFields[2].Descriptor()
	// links.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	links.TitleValidator = linksDescTitle.Validators[0].(func(string) error)
	// linksDescImage is the schema descriptor for image field.
	linksDescImage := linksFields[4].Descriptor()
	// links.ImageValidator is a validator for the "image" field. It is called by the builders before save.
	links.ImageValidator = linksDescImage.Validators[0].(func(string) error)
	// linksDescOrder is the schema descriptor for order field.
	linksDescOrder := linksFields[5].Descriptor()
	// links.DefaultOrder holds the default value on creation for the order field.
	links.DefaultOrder = linksDescOrder.Default.(int)
	// linksDescDeleted is the schema descriptor for deleted field.
	linksDescDeleted := linksFields[7].Descriptor()
	// links.DefaultDeleted holds the default value on creation for the deleted field.
	links.DefaultDeleted = linksDescDeleted.Default.(bool)
	// linksDescCreatedAt is the schema descriptor for created_at field.
	linksDescCreatedAt := linksFields[8].Descriptor()
	// links.DefaultCreatedAt holds the default value on creation for the created_at field.
	links.DefaultCreatedAt = linksDescCreatedAt.Default.(func() time.Time)
	// linksDescUpdatedAt is the schema descriptor for updated_at field.
	linksDescUpdatedAt := linksFields[9].Descriptor()
	// links.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	links.DefaultUpdatedAt = linksDescUpdatedAt.Default.(func() time.Time)
	// links.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	links.UpdateDefaultUpdatedAt = linksDescUpdatedAt.UpdateDefault.(func() time.Time)
	// linksDescID is the schema descriptor for id field.
	linksDescID := linksFields[6].Descriptor()
	// links.DefaultID holds the default value on creation for the id field.
	links.DefaultID = linksDescID.Default.(func() uuid.UUID)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescDeleted is the schema descriptor for deleted field.
	sessionDescDeleted := sessionFields[4].Descriptor()
	// session.DefaultDeleted holds the default value on creation for the deleted field.
	session.DefaultDeleted = sessionDescDeleted.Default.(bool)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[5].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	// sessionDescUpdatedAt is the schema descriptor for updated_at field.
	sessionDescUpdatedAt := sessionFields[6].Descriptor()
	// session.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	session.DefaultUpdatedAt = sessionDescUpdatedAt.Default.(func() time.Time)
	// session.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	session.UpdateDefaultUpdatedAt = sessionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// sessionDescID is the schema descriptor for id field.
	sessionDescID := sessionFields[3].Descriptor()
	// session.DefaultID holds the default value on creation for the id field.
	session.DefaultID = sessionDescID.Default.(func() uuid.UUID)
	usersFields := schema.Users{}.Fields()
	_ = usersFields
	// usersDescUsername is the schema descriptor for username field.
	usersDescUsername := usersFields[1].Descriptor()
	// users.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	users.UsernameValidator = usersDescUsername.Validators[0].(func(string) error)
	// usersDescGlobalName is the schema descriptor for global_name field.
	usersDescGlobalName := usersFields[2].Descriptor()
	// users.GlobalNameValidator is a validator for the "global_name" field. It is called by the builders before save.
	users.GlobalNameValidator = usersDescGlobalName.Validators[0].(func(string) error)
	// usersDescSlug is the schema descriptor for slug field.
	usersDescSlug := usersFields[3].Descriptor()
	// users.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	users.SlugValidator = usersDescSlug.Validators[0].(func(string) error)
	// usersDescAvatar is the schema descriptor for avatar field.
	usersDescAvatar := usersFields[4].Descriptor()
	// users.AvatarValidator is a validator for the "avatar" field. It is called by the builders before save.
	users.AvatarValidator = usersDescAvatar.Validators[0].(func(string) error)
	// usersDescDescription is the schema descriptor for description field.
	usersDescDescription := usersFields[5].Descriptor()
	// users.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	users.DescriptionValidator = usersDescDescription.Validators[0].(func(string) error)
	// usersDescAccessToken is the schema descriptor for access_token field.
	usersDescAccessToken := usersFields[6].Descriptor()
	// users.AccessTokenValidator is a validator for the "access_token" field. It is called by the builders before save.
	users.AccessTokenValidator = usersDescAccessToken.Validators[0].(func(string) error)
	// usersDescRefreshToken is the schema descriptor for refresh_token field.
	usersDescRefreshToken := usersFields[7].Descriptor()
	// users.RefreshTokenValidator is a validator for the "refresh_token" field. It is called by the builders before save.
	users.RefreshTokenValidator = usersDescRefreshToken.Validators[0].(func(string) error)
	// usersDescScope is the schema descriptor for scope field.
	usersDescScope := usersFields[8].Descriptor()
	// users.ScopeValidator is a validator for the "scope" field. It is called by the builders before save.
	users.ScopeValidator = usersDescScope.Validators[0].(func(string) error)
	// usersDescDeleted is the schema descriptor for deleted field.
	usersDescDeleted := usersFields[12].Descriptor()
	// users.DefaultDeleted holds the default value on creation for the deleted field.
	users.DefaultDeleted = usersDescDeleted.Default.(bool)
	// usersDescCreatedAt is the schema descriptor for created_at field.
	usersDescCreatedAt := usersFields[13].Descriptor()
	// users.DefaultCreatedAt holds the default value on creation for the created_at field.
	users.DefaultCreatedAt = usersDescCreatedAt.Default.(func() time.Time)
	// usersDescUpdatedAt is the schema descriptor for updated_at field.
	usersDescUpdatedAt := usersFields[14].Descriptor()
	// users.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	users.DefaultUpdatedAt = usersDescUpdatedAt.Default.(func() time.Time)
	// users.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	users.UpdateDefaultUpdatedAt = usersDescUpdatedAt.UpdateDefault.(func() time.Time)
	// usersDescID is the schema descriptor for id field.
	usersDescID := usersFields[11].Descriptor()
	// users.DefaultID holds the default value on creation for the id field.
	users.DefaultID = usersDescID.Default.(func() uuid.UUID)
}
