// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Links is the predicate function for links builders.
type Links func(*sql.Selector)

// Users is the predicate function for users builders.
type Users func(*sql.Selector)
